//
//  Temporadas.swift
//  WikiGot
//
//  Created by Yeray Castro Jiménes on 9/11/22.
//

import Foundation

struct Temporada: Hashable, Identifiable {
    var id: Int
    var nombre: String
    var episodios: Int
    var trama: String
    var primera_emision: String
    var ultima_emision: String
    var imagen: String
}

func getTemporada(id: Int) -> Temporada {
    return temporadas.filter { temporada in
        return temporada.id == id
    }.first ?? Temporada(id: -1, nombre: "", episodios: -1, trama: "", primera_emision: "", ultima_emision: "", imagen:"")
}

var temporadas: [Temporada] = [
    .init(id: 0, nombre: "Temporada 1", episodios: 10, trama: "La serie sigue las múltiples tramas de la saga Canción de hielo y fuego.2​ Comienza cuando el Rey Robert Baratheon (Mark Addy) le pide a su viejo amigo Ned Stark (Sean Bean) que realice la función de nuevo consejero real (cargo conocido como la Mano del Rey). La esposa de Ned, Catelyn (Michelle Fairley) recibe una carta de su hermana, Lysa (Kate Dickie) que le da razones para creer que la Casa Lannister, a la cual pertenece Cersei, la esposa del rey, está involucrada en la muerte de la anterior Mano del Rey. Ned debe viajar al sur con el Rey para descubrir el asesino de la Mano del Rey muerto, Jon Arryn (John Standing) y a la misma vez proteger a su familia de los Lannister. Mientras descubre las razones detrás de la muerte de Jon, desentierra el oscuro secreto concerniente a los Lannister que el propio Arryn murió tratando de revelar.\nMientras tanto, del otro lado del Mar Angosto, en el continente de Essos, el exiliado Viserys Targaryen (Harry Lloyd), hijo del anterior rey cuyo trono fue usurpado por Robert Baratheon, cree ser el verdadero heredero al trono y por lo tanto debe reclamarlo. Viserys une en matrimonio a su hermana, Daenerys Targaryen (Emilia Clarke), la cual ha sido abusada física y psicológicamente por su hermano, con el líder de la tribu de guerreros Dothraki, Khal Drogo (Jason Momoa), a cambio de un ejército para regresar a Poniente y reclamar su trono. Pero, el creciente amor de Daenerys hacia Drogo y la fortaleza que encuentra siendo la Khaleesi de la tribu, hace que los planes de Viserys fracasen rotundamente.\nEn el Muro, el hijo bastardo de Ned, Jon Snow (Kit Harington) se une a La Guardia de la Noche, una antigua hermandad jurada a proteger las tierras del sur del Muro de los salvajes que viven al norte; pero una antigua fuerza, que por mucho tiempo se pensó desaparecida, amenaza con destrucción.", primera_emision: "17 de abril de 2011", ultima_emision: "19 de junio de 2011", imagen: "Temporada1"),
    
        .init(id: 1, nombre: "Temporada 2", episodios: 10, trama: "La segunda temporada abarca varios meses en un mundo donde las estaciones duran años a la vez. Los Siete Reinos están en guerra con el Rey en el Norte, Robb Stark, luchando por ganar la independencia de su pueblo. Theon Greyjoy le pide a Robb que lo envíe a Pyke para buscar una alianza con su padre, Balon Greyjoy, aduciendo su necesidad de barcos para atacar Desembarco del Rey. Pero Theon regresa a Pyke y descubre los planes de su padre para nombrarse Rey de las Islas del Hierro. Mientras tanto, Joffrey Baratheon sostiene el Trono de Hierro con el respaldo de la poderosa Casa Lannister. Pero su tío Renly también ha reclamado el trono con el apoyo de la Casa Tyrell cuyos ejércitos son mucho más grandes. A medida que luchan por el trono, Tyrion llega a Desembarco del Rey para ayudar al rey Joffrey como su Mano solamente para hacer frente a la oposición de su hermana Cersei ahora la reina Regente.\nSin embargo, Stannis Baratheon, el hermano menor de Robert y hermano mayor de Renly, también reclama el Trono de Hierro. Un veterano de varias guerras, Stannis es conocido por ser completamente un hombre sin misericordia con sus enemigos y hará lo que es correcto incluso si tiene que destruirlo. Es aconsejado por Melisandre, un enigmática sacerdotisa roja que cree que Stannis tendrá un destino aún mayor y Ser Davos Seaworth, un hombre honesto y honorable, incómodo con los cambios en el poder en la corte de Stannis.\nEn Essos, Daenerys Targaryen ha eclosionado a los tres únicos dragones del mundo. Con su khalasar desaparecido, Daenerys y su pequeño grupo de seguidores deben encontrar un camino a través de un imponente terreno baldío y encontrar nuevos aliados para apoyar su reclamación al Trono de Hierro.\nEn el lejano norte, la Guardia de la Noche ha montado una expedición más allá del Muro en busca de exploradores desaparecidos e investigando rumores de salvajes que se reúnen en las montañas. Para Jon Snow este será un rito de paso ya que se le pide que tome decisiones difíciles, para el reino y para sí mismo.", primera_emision: "1 de abril de 2012", ultima_emision: "3 de junio de 2012", imagen: "Temporada2"),
    
        .init(id: 2, nombre: "Temporada 3", episodios: 10, trama: "Después de la derrota de Stannis Baratheon en la Batalla de Aguasnegras, El cruel rey Joffrey Baratheon ha ganado una gran victoria asegurando una alianza con la casa Tyrell; y además Joffrey ahora comanda los ejércitos más grandes en el reino y su triunfo parece inevitable. Mientras tanto, Tyrion Lannister ha perdido el poder como Mano del Rey, y siente que su padre no aprecia el servicio que prestó a la familia como Mano. Mientras tanto, Jaime Lannister continúa su intento de volver a casa, y comienza a formar un vínculo con su compañera de viaje Brienne de Tarth.\nLos Starks está perdiendo la guerra, además perdieron el apoyo de Walder Frey, después de que Robb Stark rompió su promesa al casarse con Talisa Maegyr, y muchos miembros del ejército de Robb están perdiendo la fe en él y su relación con su madre Catelyn Tully también se ha vuelto fría después de que ella liberó a Jaime Lannister. Mientras, Bran y Rickon Stark continúan su viaje hacia el norte con unos nuevos aliados extraños que son los hermanos Reed. Theon Greyjoy debe enfrentar las consecuencias de sus acciones en Invernalia y será torturado por Ramsay. Arya Stark continua en su viaje a casa con Gendry y Pastel caliente, pero en su camino se encuentra con La Hermandad sin Estandartes y con otra persona que es Sandor Clegane. Sansa Stark permanece en Kingslanding como una rehén de los Lannister, pero se le ofrece ayuda tanto por el traicionero Petyr Baelish como por los Tyrell.\nEn Rocadragón, aparece un hombre que sobrevivió después de ser aplastado en la batalla de Aguasnegras: Ser Davos. Pero es encarcelado después de intentar matar a Melisandre, quien todavía cree que su dios, el Señor de la Luz, ayudará a Stannis.\nMás allá del muro, Jon Nieve se une al ejército del Rey-más-allá-del-muro Mance Rayder, con el objetivo de espiar a los salvajes. Pero rompe sus votos con una mujer salvaje Ygritte,por lo que tendrá que elegir entre ella o la Guardia de la Noche. Por otro lado, muchos de los hombres de la guardia también cuestionan sus votos, poniendo en peligro las vidas del Lord Comandante Jeor Mormont y Samwell Tarly.\nEn Essos, Daenerys Targaryen continúa su viaje para recuperar los siete reinos. Ella tiene un nuevo compañero, Barristan Selmy, y Jorah Mormont. Además contempla la compra de los Inmaculados, un ejército de élite de eunucos severamente entrenados que son controlados por un amo cruel con una joven traductora inteligente, Missandei.", primera_emision: "31 de marzo de 2013", ultima_emision: "9 de junio de 2013", imagen: "Temporada3"),
    
        .init(id: 3, nombre: "Temporada 4", episodios: 10, trama: "Al obtener la victoria de la guerra con el apoyo de la Casa Tyrell, los Lannister impulsan el matrimonio del rey Joffrey Baratheon y Margaery Tyrell, en donde la boda acaba con el reinado del joven sádico tras ser envenenado por la matriarca Tyrell, Olenna. Dolida por la pérdida, Cersei Lannister acusa a su hermano Tyrion Lannister y a su esposa Sansa Stark del asesinato de su hijo. Mientras Tyrion recibe un juicio por su padre Tywin Lannister, Sansa escapa de la capital con ayuda de Petyr Baelish al Valle de Arryn donde sufre por actos de su celosa tía, Lysa Arryn. Cuando Oberyn Martell pierde el juicio por combate con Ser Gregor Clegane, Tyrion es sentenciado a muerte, pero su hermano Jaime Lannister lo libera; y con ira de venganza asesina a su ex-amante Shae y a su padre.\nTras la destrucción de la Casa Stark, Arya Stark es obligada a confiar en la protección de Sandor Clegane, que tras un cruce con Brienne de Tarth logra escapar sola a Braavos. Más allá del Muro, Bran Stark, acompañado por Hodor, Jojen y Meera Reed, sigue con su viaje de encontrar el Cuervo de tres ojos. Tras la muerte de Jojen y encontrando al Cuervo de tres ojos, Bran descubre que el será el siguiente Cuervo.\nEn el Muro, Jon Nieve y la guardia de la noche alza su victoria contra las fuerzas de Mance Rayder, aunque Jon pierde a su amada salvaje Ygritte. Mientras tanto, Stannis Baratheon, como legítimo heredero de su hermano mayor el rey Robert, todavía se niega a rendirse a pesar de tener un ejército reducido. Sin embargo, siguiendo el consejo de Melisandre ha centrado su atención en el Norte, sobre la amenaza de los salvajes que marcha contra el Muro.\nEn Essos, con su tres dragones, sus fieles aliados y ejército, Daenerys Targaryen se convierte en reina de Meereen. Aunque la muerte Joffrey le da la oportunidad a Daenerys de tomar los siete reinos, ella decide quedarse y gobernar Meereen para convertirse en una buena reina.", primera_emision: "6 de abril de 2014", ultima_emision: "15 de junio de 2014", imagen: "Temporada4"),
    
        .init(id: 4, nombre: "Temporada 5", episodios: 10, trama: "En Meereen, los Hijos de la Arpía comienza a rebelarse contra el régimen de Daenerys Targaryen, entonces para recuperar la paz y el control de la ciudad, Daenerys cumple con la solicitud de reabrir los fosos de combate mientras toma a Hizdahr zo Loraq como su esposo. Mientras tanto, Tyrion Lannister y Varys llegan a Pentos y comienzan su viaje a Meereen para conocer a Daenerys. Pasan por Volantis, donde Tyrion es secuestrado por Jorah Mormont, quien lo lleva a Meereen como una forma de redimirse a Daenerys. Tras otro ataque de los Hijos de la Arpía; Daenerys el sacada de la ciudad por su dragón, Drogon; dejando a Tyrion, Missandei y Gusano Gris como gobernantes de Meereen.\nEn el Muro, el recién elegido Lord Comandante de la Guardia de la noche, Jon Nieve forma una alianza con los salvajes para derrotar a los Caminantes Blancos; pero esta decisión hace que una parte de sus compañeros de la guardia de la noche le ganen un odio, que con impulsos liderados por Alliser Thorne, haga que asesinen a Jon.\nEn Invernalia, Sansa Stark se casa con Ramsay Bolton por obra de Petyr Baelish para formar una alianza entre el Valle y los Bolton. Posteriormente Sansa es sometida a los actos perversos de Ramsay. Mientras tanto, Stannis Baratheon planear invadir a Invernalia, pero al ver sus pocas tropas y la nieve, Stannis en un último intento por ganar; hace que Melisandre sacrifique a su hija Shireen Baratheon por la victoria. Para mala suerte de Stannis, los embrujos no lo ayudan a ganar, es vencido por Ramsay y asesinado por Brienne de Tarth. Aprovechando la batalla de los Bolton contra Baratheon, Sansa escapa de Invernalia con ayuda de Theon Greyjoy.\nEn Desembarco del Rey, tras la boda de Margaery Tyrell y el rey Tommen Baratheon, y al ver como la joven Tyrell es una amenaza a su poder, Cersei Lannister hace renacer la Fe militante que encarcela a los hermanos Tyrell. Pero Cersei no logra predecir el poder que la religión llega a tener gracias a su líder el Gorrión Supremo, que encarcela a Cersei por sus pecados. Tras no haber otro modo de liberación, la reina madre decide confesar sus pecados para regresar con su hijo; pero antes realiza la vergonzosa caminata de expiación.\nEn Dorne, las serpientes de arena junto con Ellaria Arena, buscan venganza por la muerte de Oberyn Martell. Después de que Dorne enviara un mensaje amenazante al Desembarco del Rey, Jaime Lannister y Bronn son enviados para rescatar a Myrcella Baratheon. Aunque las Arenas logran ser detenidas inicialmente por Doran Martell; al final logran matar a Myrcella mientras se dirigía con Jaime a casa. Arya Stark llega a Braavos y comienza a entrenar con los Hombres sin rostro, guiados por Jaqen H'ghar y la niña abandonada.", primera_emision: "12 de abril de 2015", ultima_emision: "14 de junio de 2015", imagen: "Temporada5"),
    
        .init(id: 5, nombre: "Temporada 6", episodios: 10, trama: "Tras su escape de Invernalia, Sansa Stark viaja al Muro con Brienne de Tarth para reencontrarse con su hermano Jon Nieve que fue asesinado por los de la Guardia de la noche pero será revivido gracias a Melisandre, mientras que Theon Greyjoy regresa a las Islas de Hierro. En Invernalia, Ramsay Bolton asegura su reclamo del Norte tras matar a su padre Roose. Más allá del Muro, Bran Stark entrena con el Cuervo de Tres Ojos, pero alerta al Rey de la Noche, quien lanza un ataque a la guarida.\nEn Desembarco del Rey, Jaime Lannister y el ejército Tyrell intentan liberar a Margaery y Loras, pero Margaery ha abrazado la Fe de los Siete y Tommen forja una alianza con la Fe. Tommen releva a Jaime de sus deberes como Guardia Real y le ordena que ayude a Walder Frey al expulsar al Pez negro de Aguasdulces. Mientras Cersei debe esperar su juicio. En Dorne, Ellaria Arena y las tres hijas de Oberyn Martell matan a Doran y Trystane Martell y toman el control de Dorne.\nEn Braavos, Arya continúa su entrenamiento con los Hombres Sin Rostro; y pronto recupera la vista. Mientras tanto Sam Tarly, Gilly y su hijo viajan a la Ciudadela.\nEn Essos, Daenerys Targaryen es capturada por Khal Moro quien la lleva ante los khals pero los quema vivos cuando se niegan a servirla y toman el mando de los Dothraki y en Meeren Tyrion Lannister y Varys trae una paz estable a Meereen.", primera_emision: "24 de abril de 2016", ultima_emision: "26 de junio de 2016", imagen: "Temporada6"),
    
        .init(id: 6, nombre: "Temporada 7", episodios: 7, trama: "La séptima temporada se centra principalmente en la convergencia de los principales argumentos de la serie, con eventos importantes como Daenerys Targaryen llegando a Westeros con su ejército y tres dragones y librando una guerra contra los Lannister, Jon Snow forjando una alianza con Daenerys en un intento de unir su fuerzas contra el ejército del Caminante Blanco, Arya y Bran regresando a Winterfell y reuniéndose con su hermana Sansa, y el ejército de los muertos rompiendo el Muro (con la ayuda de un dragón) y entrando en los Siete Reinos.", primera_emision: "16 de julio de 2017", ultima_emision: "27 de agosto de 2017", imagen: "Temporada7"),
    
        .init(id: 7, nombre: "Temporada 8", episodios: 6, trama: "La octava y última temporada de la serie de televisión de drama y fantasía Game of Thrones, producida por HBO, se estrenó el 14 de abril de 2019. La filmación comenzó oficialmente el 23 de octubre de 2017 y concluyó en julio de 2018.\nA diferencia de las primeras seis temporadas, en las que cada una tuvo diez episodios y la séptima que tuvo siete, la octava temporada tuvo seis episodios. Al igual que la temporada anterior, constó en gran medida de contenido original que no se encuentra actualmente en la Canción de hielo y fuego de George R. R. Martin, y también se adaptó material que Martin había revelado a productores sobre las próximas novelas de la serie, Vientos de invierno y Sueño de primavera. La temporada fue adaptada para televisión por David Benioff y D.B. Weiss.", primera_emision: "14 de abril de 2019", ultima_emision: "19 de mayo de 2019", imagen: "Temporada8")

]
    
    
    
